version: '3.8'

services:
  db:
    container_name: postgresql
    image: postgres:16
    volumes:
      - ./exam_db_dump.sql:/docker-entrypoint-initdb.d/exam_db_dump.sql
    environment:
      - POSTGRES_DB=exam
      - POSTGRES_USER=moon
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - exam_network

  django:
    container_name: django
    build: .
    command: gunicorn exam.wsgi:application --bind 0.0.0.0:8000
      #command: gunicorn exam.wsgi:application --bind unix:/work/django/exam/run/gunicorn.sock
    volumes:
      - .:/work/django/exam
      - static_volume:/work/django/exam/staticfiles
      - socket_volume:/work/django/exam/run
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://moon:1234@db:5432/exam
    networks:
      - exam_network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/exam.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/work/django/exam/staticfiles
      - socket_volume:/work/django/exam/run
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - exam_network

volumes:
  postgres_data:
  static_volume:
  socket_volume:

networks:
  exam_network:
    name: exam_network
