# Generated by Django 4.2.13 on 2024-07-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table13',
            new_name='PDF1',
        ),
        migrations.RenameModel(
            old_name='Table15',
            new_name='PDF2',
        ),
        migrations.RenameModel(
            old_name='Table12',
            new_name='PDF3',
        ),
        migrations.RenameModel(
            old_name='Table14',
            new_name='PDF4',
        ),
        migrations.RenameField(
            model_name='pdf1',
            old_name='col3',
            new_name='col2',
        ),
        migrations.RenameField(
            model_name='pdf2',
            old_name='col5',
            new_name='col3',
        ),
        migrations.RenameField(
            model_name='pdf3',
            old_name='col2',
            new_name='col4',
        ),
        migrations.RenameField(
            model_name='pdf4',
            old_name='col4',
            new_name='col5',
        ),
    ]
