# Generated by Django 4.2.11 on 2024-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
    ]
