# Generated by Django 4.2.11 on 2024-07-08 07:03

import aws.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_alter_aws_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='question_text',
            field=aws.models.LastLineBreakTextField(),
        ),
    ]
