# Generated by Django 4.2.13 on 2024-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_alter_aws_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aws',
            name='question_text_last_line',
            field=models.TextField(blank=True),
        ),
    ]
