# Generated by Django 4.2.13 on 2024-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nca',
            name='choice_a',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nca',
            name='choice_b',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nca',
            name='choice_c',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nca',
            name='choice_d',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nca',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
