apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_SETTINGS_MODULE: "exam.settings"
  DATABASE_URL: "postgres://moon:1234@postgresql:5432/linux"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.49.2"
  STATIC_URL: "/static/"
  STATIC_ROOT: "/work/django/exam/staticfiles"
